version: '3.8'

services:
  data-service:
    build: ./data
    ports:
      - "5000:5000"
    volumes:
      - ./products_1.json:/app/products_1.json
    environment:
      - INDEX_NAME=products-index
      - DIMENSION=512
      - PRODUCTS_FILE=products_1.json
      - LIMIT=10
      - VERBOSE=true
      - FLASK_ENV=production
    restart: unless-stopped
