version: '3.8'

services:
  data-service:
    build: ./data
    ports:
      - "5000:5000"
    volumes:
      - ./products_1.json:/app/products_1.json
    environment:
      - FLASK_ENV=production
    restart: unless-stopped