version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey123}
      - MEILI_ENV=development
      - MEILI_HTTP_ADDR=0.0.0.0:7700    # Added to explicitly set binding address
      - MEILI_NO_ANALYTICS=true          # Added to reduce startup overhead
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s
    restart: unless-stopped

  data-service:
    build: ./data
    ports:
      - "5000:5000"
    volumes:
      - ./data-service/products_1.json:/app/products_1.json
    environment:
      - INDEX_NAME=products-index
      - DIMENSION=512
      - PRODUCTS_FILE=products_1.json
      - LIMIT=10
      - VERBOSE=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/products_db
      - REDIS_URL=redis://redis:6379/0
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILISEARCH_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey123}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    restart: on-failure


  backend:
    build: ./search_engine
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DATA_SERVICE_URL=http://data-service:5000
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILISEARCH_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey123}
    volumes:
      - ./backend:/app
    depends_on:
      - data-service
    command: python manage2.py runserver 0.0.0.0:8000
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
  meili_data:

networks:
  default:
    driver: bridge